const transformer = require('./transformer.js')
const responseZ = require('./stubs/response-z.json')
const responseX = require('./stubs/response-x.json') 
console.log(JSON.stringify(transformer(responseZ), null, 2))
console.log(JSON.stringify(transformer(responseX), null, 2))